### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by jiisanda** [LemonOSProject/LemonOS#50]
System Specs:
Windows:  11
Processor :- intel i5
Ram : 16GB

commands:
```bash
git clone  https://github.com/LemonOSProject/LemonOS.git

cd LemonOs/Scripts

sudo ./docker-init.sh

```

```
ERROR: Neither directory contains a build file meson.build.
Traceback (most recent call last):
  File "/usr/local/bin/xbstrap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/xbstrap/__init__.py", line 896, in main
    args._impl(args)
  File "/usr/local/lib/python3.10/dist-packages/xbstrap/__init__.py", line 867, in do_execute_manifest
    xbstrap.base.execute_manifest(manifest)
  File "/usr/local/lib/python3.10/dist-packages/xbstrap/base.py", line 1697, in execute_manifest
    subprocess.check_call(args, env=environ, cwd=workdir, stdout=output, stderr=output)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['meson', '--cross=/var/LemonOS/Scripts/lemon-crossfile.txt', '-Dheaders_only=True', '-Dlinux_kernel_headers=/var/LemonOS/Build/packages/linux-headers/usr/include', '--prefix=/system', '/var/LemonOS/mlibc']' returned non-zero exit status 1.
xbstrap: Action configure of package mlibc-headers failed
```

**Comment by theanshulroy** [comment]
Is the project's source code includes a 'meson.build' file?

**Comment by fido2020** [comment]
Ah, did you initialize the git submodules correctly? It looks like mlibc sources might be missing

**Comment by jiisanda** [comment]
Yaa, I got that. It seems like the git submodules were not initialized correctly, resulting in missing mlibc sources. 

Thanks.
